import Head from "next/head";
import Script from "next/script";
import { OrbitControls } from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";
import { Suspense, useMemo, useRef } from "react";
import { Color } from "three";
import MovingPlane from "../components/MovingPlane/MovingPlane";
import Blob from "../components/Blob/Blob";
import Gradient from "../components/Gradient/Gradient";
import Planet from "../components/Planet/Planet";
import SphereGradient from "../components/SphereGradient/SphereGradient";
import Stripe from "../components/Stripe/Stripe";
import Image from "../components/Image/Image";
import ImageWave from "../components/Image/Image";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="bg-black h-[100vh] w-[100vw]">
      <Canvas camera={{ position: [0.0, 0.0, 8.0] }}>
      {/* <ambientLight intensity={0.03} />
      <directionalLight position={[0.3, 0.15, 0.0]} intensity={2} /> */}

      <Suspense fallback={null}>
      <ImageWave/>
      <OrbitControls />
      </Suspense>
      
      </Canvas>
      </div>

    </div>
  );
}
